// automatically generated by the FlatBuffers compiler, do not modify

package com.mbtool.daemon.v3;

import com.google.flatbuffers.*;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MbSetKernelError extends Table {
  public static MbSetKernelError getRootAsMbSetKernelError(ByteBuffer _bb) { return getRootAsMbSetKernelError(_bb, new MbSetKernelError()); }
  public static MbSetKernelError getRootAsMbSetKernelError(ByteBuffer _bb, MbSetKernelError obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public MbSetKernelError __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startMbSetKernelError(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endMbSetKernelError(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

