// automatically generated by the FlatBuffers compiler, do not modify

package com.mbtool.daemon.v3;

import com.google.flatbuffers.*;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class RebootError extends Table {
  public static RebootError getRootAsRebootError(ByteBuffer _bb) { return getRootAsRebootError(_bb, new RebootError()); }
  public static RebootError getRootAsRebootError(ByteBuffer _bb, RebootError obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public RebootError __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startRebootError(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endRebootError(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

