// automatically generated by the FlatBuffers compiler, do not modify

package com.mbtool.daemon.v3;

import com.google.flatbuffers.*;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ShutdownError extends Table {
  public static ShutdownError getRootAsShutdownError(ByteBuffer _bb) { return getRootAsShutdownError(_bb, new ShutdownError()); }
  public static ShutdownError getRootAsShutdownError(ByteBuffer _bb, ShutdownError obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ShutdownError __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startShutdownError(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endShutdownError(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

